### ISSUE TITLE
Create simplified new child/relationship creation menu for UML Class diagram

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-umllight#11]
The new child / relationship creation menu should only contain the following UML concepts (equal to #5):

* [ ] Class
* [ ] Comment
* [ ] DataType
* [ ] Enumeration
* [ ] Enumeration Literal
* [ ] Interface
* [ ] Interface Realization
* [ ] Primitive Type
* [ ] Operation
* [ ] Package
* [ ] Property
* [ ] Parameter
* [ ] Aggregation (composition, aggregation)
* [ ] Association
* [ ] Association Class
* [ ] Generalization
* [ ] Link
* [ ] Realization
* [ ] Visibility (public, private, protected)
* [ ] Dependency
* [ ] Multiplicity

**Comment by cdamus** [comment]
Note that, currently, it is permitted to create an `EnumerationLiteral` as a packaged element.  This doesn't make sense because enumeration literals are required to have an `Enumeration` as owner.

Also, `ValueSpecification` is a kind of `PackageableElement`, so the **New Child** menu for packages currently has the various kinds of literals and expressions.  This is really only useful for templates (in particular, as arguments in template parameter substitutions), which we don't have in _UML Light_, so I think we shouldn't create these in packages.

**Comment by planger** [comment]
Thanks for your work on this! I think we'll need to check with our stakeholders, whether we have to further limit the new child menu for elements that may recursively contain each other, e.g. classes and nested classes. Via the diagram we can't create them -- that's good; however, using the new child creation menu, we could create nested classes. Not sure this is a road we need to go, but I just wanted to mention it.

**Comment by cdamus** [comment]
Okay, cool.  It's easy enough to do with filters and/or edit advice if we need to.
