### ISSUE TITLE
Create simplified new child/relationship creation menu for UML Package diagram

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-umllight#13]
The new child / relationship creation menu should only contain the following UML concepts (equal to #7):

* [ ] Comment
* [ ] Model
* [ ] Package
* [ ] Containment Link
* [ ] Dependency
* [ ] Link
* [ ] PackageImport

**Comment by cdamus** [comment]
@planger I think there are some concepts missing from the list in this requirement:

- Constraint:  sure, these can be complex, but even the most basic model needs to be able to specify constraints on the system that it describes
- Profile and Profile Application:  if we can draw packages, we should be able to apply profiles.  Without profiling, it will be difficult for users to customize the *UML Light* for their domains

Also, I think the Link item doesn't make sense:  that's an instance-specification concept, which we've excluded from *UML Light* and wouldn't be in a package diagram, anyways.

Finally, I wonder since we have Package Import on the list, whether we shouldn't also have Element Import?  It seems more basic than the Package Import.

**Comment by cdamus** [comment]
Also, it's important to note that a bunch of things that are presented in other diagrams (classes, use cases, actors, behaviors) need to be in the **New Child** menu of a package, even though they cannot be visualized in a package diagram.

**Comment by cdamus** [comment]
In fact, I think it makes sense anyways to define just a single creation-menu model for each of the *New Child* and *New Relationship* menus, which is what I have in progress now.

**Comment by cdamus** [comment]
Fixed with pull #22.
