### ISSUE TITLE
Define shown features in property views

### ISSUE THREAD

**Issue by planger** [eclipsesource/papyrus-umllight#18]
We require input on which features are to be shown in the properties views and whether we need to simplify those in some aspects for some concepts.

**UML Use Case**

- [ ] Package
- [ ] Subject
- [ ] Actor
- [ ] Use Case
- [ ] Comment
- [ ] Association
- [ ] Generalization
- [ ] Include
- [ ] Extend
- [ ] Comment link

 
**Activity Diagram**

- [ ] Activity
- [ ] Initial Node
- [ ] Final Node
- [ ] Activity final
- [ ] Decision node
- [ ] Merge node
- [ ] Join node
- [ ] Fork node
- [ ] Opaque Action
- [ ] Comment
- [ ] Control Flow
- [ ] Link
- [ ] Action
- [ ] Call BehaviorAction
- [ ] CallOperation Action
- [ ] AcceptEventAction
- [ ] Pin
- [ ] InputPin
- [ ] OutputPin

 
**Class Diagram**

- [x] Class
- [x] Comment
- [x] DataType
- [x] Enumeration
- [x] Enumeration Literal
- [x] Interface
- [x] Interface Realization
- [x] Primitive Type
- [x] Operation
- [x] Package
- [x] Property
- [x] Operation
- [x] Parameter
- [x] Aggregation (composition, aggregation)
- [x] Association
- [x] Association Class
- [x] Generalization
- [x] Link
- [x] Realization
- [x] Visibility (public, private, protected)
- [x] Dependency
- [x] Multiplicity

 
**State Machine**

- [x] State
- [x] Initial
- [x] FinalState
- [x] Choice
- [x] Junction
- [x] Comment
- [x] Transition
- [x] Link

 
**Package Diagram**

- [x] Comment
- [x] Model
- [x] Package
- [x] Containment Link
- [x] Dependency
- [x] Link
- [x] PackageImport

 
**Sequence Diagram**

- [ ] OccurrenceSpecification
- [ ] Executation Specification
- [ ] Interaction
- [ ] Action Execution Specification
- [ ] Comment
- [ ] Interaction Use
- [ ] Lifeline
- [ ] Message Async
- [ ] Message Sync
- [ ] Message Occurence Specification
- [ ] MessageSort
- [ ] MessageEnd
- [ ] CallEvent
- [ ] SignalEvent
- [ ] OpaqueBehavior
- [ ] Link

**Comment by cdamus** [comment]
A proposal for properties of Package Diagram, Class Diagram, Use Case Diagram, and Sequence Diagram concepts:

[Properties View.pdf](https://github.com/eclipsesource/papyrus-umllight/files/2600522/Properties.View.pdf)

**Comment by planger** [comment]
Nice proposal, thanks @cdamus!

**Comment by cdamus** [comment]
And a proposal for the other two diagram types, the State Machine Diagram and the Activity Diagram:

[Properties View II.pdf](https://github.com/eclipsesource/papyrus-umllight/files/2630049/Properties.View.II.pdf)

**Comment by tortmayr** [comment]
@cdamus  Very nice proposal
I'm wondering though if we really need <i>Label</i> property in the context of UML Light.

**Comment by cdamus** [comment]
The _Label_ is an extra-UMLism provided by Papyrus that I imagine is particularly interesting for presenting diagrams in multiple languages in the context of system documentation, and I imagine documentation being a prime use case for _UML Light_.  So, it seems harmless **but** it does imply the management of additional `properties` resources that complicate a user's life.  And it's non-standard.  So I would support suppressing it, but perhaps our stakeholders should weigh in on the question as it could be valuable for that documentation use case.

**Comment by cdamus** [comment]
One aspect of this that we will have to address is the problem of what to do about the default UML property views provided by _Papyrus UML_.  As we develop our custom properties views, we will be testing them by disabling the **UML Metamodel (plugin)** context in the preferences because otherwise we won't see any effective change.

So, our work won't help users unless that context is disabled, but disabling it also affects non-light UML models.  Unfortunately, Papyrus has neglected (so far) to tie properties contexts to the _architecture model_.  So, we could (once we have finished the coverage of properties for all of the diagrams) implement an Equinox XSLT transform that sets the default enablement of Papyrus's UML properties context to `false` on the understanding that users may have to explicitly enable it for themselves if they need also to use full UML.

Comments, @planger and @tortmayr?

**Comment by planger** [comment]
Right, in Papyrus-IM we added an activator that hides them at runtime via a [ContextConfigurator](https://git.eclipse.org/c/papyrus/org.eclipse.papyrus-informationmodeling.git/tree/plugins/org.eclipse.papyrus.information.modeling.simplifiedui/src/org/eclipse/papyrus/information/modeling/simplifiedui/internal/ContextConfigurator.java). I think we can do the same but put it in an own plug-in, so that we can easily build with and without this activator. Similar as we did with all the simplification mechanisms that are rather intrusive.

What do you think?

**Comment by cdamus** [comment]
Another aspect that I've noticed in testing is that the green ➕ buttons in the **Properties** view that create new elements suggest metaclasses that are not included in the _UML Light_ subset.  We need to filter those out.  I'm not sure whether it is sufficient to contribute _edit-helper advice_ that disables creation of these elements as we do for trimming the **New Child** menu.  In any case, it should be investigated because this is a _leak_ of concepts that we don't want the user to face.

**Comment by CharlesAtZelig** [comment]
This is a good list of simplifications.
I would prefer to keep "isQuery" for operations, simply because I have used it fairly often during early modeling, especially of datastores, to provide a hint to the user. But I am not dogmatic about it.
I would also like to mention that, during the first "election" of capabilities for Papyrus UML Light, mutiplicity and subject were explicitly out.

**Comment by planger** [comment]
> I would also like to mention that, during the first "election" of capabilities for Papyrus UML Light, mutiplicity and subject were explicitly out.

In the final election those were in again. I'm not against removing them, but for now I'd like to stick to the final list, until there is a common agreement to change it.

**Comment by CharlesAtZelig** [comment]
OK. agreed. I was not even aware that there had been more elections.
And where could I find the results of the latest so I can stop bother people about this?

And what are your thoughts qbout my comment on the "isQuery?

**Comment by planger** [comment]
> OK. agreed. I was not even aware that there had been more elections.
> And where could I find the results of the latest so I can stop bother people about this?

I forwarded you the mail to the steering committee about the decision. It (hopefully) should correspond to the list we have in the descriptions of the respective github issues, such as this one.

> And what are your thoughts qbout my comment on the "isQuery?

I'm fine with keeping it. I think the semantics is simple enough to keep it anyway.

**Comment by cdamus** [comment]
The problem I have with `isQuery` is that it asserts that an operation is free of side-effects, which is interesting mostly for active classes (which we don't have in _UML Light_) and other concurrency concerns that we don't support.  Plus access from OCL (which I don't know what its relationship to _UML Light_ is supposed to be), inasmuch as OCL expressions may only call query operations.

Note that not including a property in the **UML** tab doesn't make it unavailable.  It's still presented in the **Advanced** tab.  To me, this property feels sufficiently "advanced".

**Comment by cdamus** [comment]
> Another aspect that I've noticed in testing is that the green ➕ buttons in the **Properties** view that create new elements suggest metaclasses that are not included in the _UML Light_ subset.

For the sequence diagram properties view (#62), I'm working on a custom `ModelElement` implementing the filtering of creatable types and other concerns.  This apply generically to all of the diagrams via the _Properties View Context Model_ that we already have in place.

**Comment by planger** [comment]
@CharlesAtZelig @cdamus Thanks for the discussion! These are all valid points, but I agree that given the scope of this project, it is not worth discussing this further.
I think the for the use case of UMLLight, simplicity should have higher priority than including certain additional aspects; especially if those aspects can still be specified in the not-so-convenient but available advanced property tab. Thus, for the sake of keeping it as simple as possible, I'd remove `isQuery` then.

**Comment by cdamus** [comment]
Per discussion in #10, we need to add `ObjectFlow` to the _Acitivty Diagram_.  For that, I would suggest a similar treatment as for `ControlFlow`, plus suppression of the multicast-related properties:

![screen shot 2018-12-18 at 09 44 40](https://user-images.githubusercontent.com/1615558/50161518-03070b80-02aa-11e9-9c39-018b035c3567.png)

**Comment by cdamus** [comment]
For `Parameter`, the proposal indicates that we should have edit advice to set the `effect` in accordance with a plausible default for the `direction`.  However, looking at this again, I see that UML metamodel has the `effect` as optional (`[0..1]` multiplicity) which in the EMF-based implementation is an "unsettable" feature.  Because EMF requires the `effect` to have a value in the Java implementation (it has an enumeration type), it looks like it's set even when it isn't.  And by default, it isn't set, so I think we do not need the proposed advice.

**Comment by planger** [comment]
:+1: Great thanks for clarifying.
